// <auto-generated />
using System;
using Artikelplanung.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artikelplanung.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921191503_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Artikelplanung.Web.Models.ArtikelEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikelname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean")
                        .HasColumnType("TEXT");

                    b.Property<string>("EingetragenVon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notiz")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioritaet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quelle")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ean");

                    b.ToTable("ArtikelEintraege");
                });

            modelBuilder.Entity("Artikelplanung.Web.Models.ImportierteSpalte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikelEintragId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Spaltenname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wert")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelEintragId");

                    b.ToTable("ImportierteSpalten");
                });

            modelBuilder.Entity("Artikelplanung.Web.Models.ImportierteSpalte", b =>
                {
                    b.HasOne("Artikelplanung.Web.Models.ArtikelEintrag", null)
                        .WithMany("ImportierteSpalten")
                        .HasForeignKey("ArtikelEintragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Artikelplanung.Web.Models.ArtikelEintrag", b =>
                {
                    b.Navigation("ImportierteSpalten");
                });
#pragma warning restore 612, 618
        }
    }
}
